# Generated by Django 4.0.2 on 2022-05-12 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_messages_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-created_at']},
        ),
    ]
